#!/bin/bash

set -o errexit
set -o pipefail

echo " => Creating Python virtual environment"
python3 -m venv venv

# shellcheck disable=SC1091
. venv/bin/activate

echo " => Creating distribution"
DEST_DIR=$(mktemp -d)
python setup.py sdist bdist_wheel -d "$DEST_DIR"

echo " => Uploading package"
pushd "$DEST_DIR"
twine upload bankroll-*