#!/bin/bash

set -o errexit
set -o pipefail

# shellcheck disable=SC1091
. venv/bin/activate

echo " => Uninstalling development dependencies"
pip uninstall -r requirements.txt --yes

echo
echo " => Installing bankroll"

pip install -U .

echo
echo " => Testing bankroll --help"

bankroll --help
