#!/bin/bash

set -o errexit
set -o pipefail

if [ ! "$CIRCLECI" ]
then
    echo " => Creating Python virtual environment"
    python3 -m venv venv

    # shellcheck disable=SC1091
    . venv/bin/activate

    echo " => Uninstalling development dependencies"
    pip uninstall -q -r requirements.txt --yes
fi

echo
echo " => Installing bankroll"

pip install -q -U .

echo
echo " => Testing bankroll --help"

bankroll --help
