#!/bin/bash

set -o errexit
set -o pipefail

# shellcheck disable=SC1091
. venv/bin/activate

export HYPOTHESIS_PROFILE=ci

if [ "$CIRCLECI" ]
then
    python -m unittest -v -- $(circleci tests glob "tests/test_*.py" | circleci tests split --split-by=timings)
else
    python -m unittest -v -- tests/test_*.py
fi
