#!/bin/bash

set -o errexit
set -o pipefail

# shellcheck disable=SC1091
. venv/bin/activate

echo " => Uninstalling development dependencies"
pip uninstall -r requirements.txt --yes

script/install_twsapi "$@"

echo
echo " => Installing bankroll"

pip install .

echo
echo " => Testing bankroll"

bankroll --help >/dev/null