#!/bin/bash

set -o errexit
set -o pipefail

# shellcheck disable=SC1091
. venv/bin/activate

export HYPOTHESIS_PROFILE=ci

if [ "$CIRCLECI" ]
then
    TEST_FILES=$(circleci tests glob "tests/*.py" | circleci tests split --split-by=timings)
    python -m unittest -v -- "${TEST_FILES}"
else
    python -m unittest -v -- tests/*.py
fi
